# # See https://pre-commit.com for more information
# # See https://pre-commit.com/hooks.html for more hooks
exclude: "^tests/snapshots/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=100000"] # Set the maximum file size to 2048 KB (2 MB)
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: mixed-line-ending

  # Removes unnecessary # noqa comments.
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  # Check for blanket (overly broad) noqa comments and encourage type annotations.
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--safe]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==24.4.2]
      - id: nbqa-isort
        additional_dependencies: [isort==5.13.2]
        args: [--profile=black]
      - id: nbqa-ruff
        additional_dependencies: [ruff==0.3.4]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write, --config, app/frontend/.prettierrc.json]
        types_or: [css, json, javascript, ts, tsx, html]
        additional_dependencies:
          - prettier@3.3.3
